### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by jallwork** [alexa/skill-sample-nodejs-first-apl-skill#5]
On the Why Build Multimodal Alexa Skills? page:
https://github.com/alexa-samples/skill-sample-nodejs-first-apl-skill/blob/master/modules/module1.adoc

the link to Next Module (2) doesn't work.
The link address is:
https://github.com/alexa-samples/skill-sample-nodejs-first-apl-skill/blob/master/modules/module2.html

**Comment by aszk** [comment]
It seems this has been updated.
