### ISSUE TITLE
can't use "documents" as folder

### ISSUE THREAD

**Issue by jallwork** [alexa/skill-sample-nodejs-first-apl-skill#6]
I have saved launchDocument.json in a folder called documents. When I run the code using: 
const launchDocument = require('./documents/launchDocument.json');

 I get the error:
 "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '/documents/launchDocument.json'",

If I save the launchDocument.json in the same folder as index.js, and use the code:
const launchDocument = require("launchDocument.json");

it works.

If I save the launchDocument.json in a folder called 'docs' and use the code:
const launchDocument = require('./docs/launchDocument.json');

it also works. Why can't I use the folder called 'documents'?
See attached for code and layout
![files](https://user-images.githubusercontent.com/35535813/124151919-f4108f00-da8a-11eb-9911-1fa0ab465ea3.png)

**Comment by aszk** [comment]
Hello jallwork, I'd like to make sure if this issue persists. I couldn't reproduce it.

**Comment by jallwork** [comment]
I can't remember, and don't recall having the problem since, so close it. Thanks for looking

**Comment by aszk** [comment]
@jallwork thank you for your confirmation. Please let me know if you reproduce the issue again.
